import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { increment, decrement, getCount } from "../Blockchain";
const Home: NextPage = () => {
  const [count, setCount] = useState(0);
  const obtainCount = async () => {
    const res = await getCount();
    console.log(res);
    const resInInt = parseInt(res, 10);
    console.log(resInInt);
    setCount(resInInt);
  };

  const increase = async () => {
    const res = await increment();
    console.log(res);
    await obtainCount();
  };
  const decrease = async () => {
    const res = await decrement();
    console.log(res);
    await obtainCount();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Death Counter</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBUWFRgWFRYYGBgYGhoYGRgcGBoYGhoYGRgaGhwYGhocIS4lHB4rIRoYJjgmKy8xNTU1GiU7QDs0Py40NTEBDAwMEA8QGhISHDQhISExNDQxNDQ0MTQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQxMTQ0NDQ0NP/AABEIAMIBAwMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAACAAEDBAUGB//EADkQAAEDAgQDBwMCBgICAwAAAAEAAhEDIQQSMUFRYXEFIoGRobHwMsHRE+EGQlJicvEjgpKyFDPC/8QAGAEAAwEBAAAAAAAAAAAAAAAAAAECAwT/xAAiEQEBAAICAwADAAMAAAAAAAAAAQIRITEDEkEiMlFhcYH/2gAMAwEAAhEDEQA/APKQE6SdYOoydOAnhBmARAJBOAgElCcBPCAZPCfLafko3tEmDaTBPBBghOxskAb2UoounLFxrygSZ4WB8lrdjdmBzmF+jnt5Q0d6epAPhfcBBWyHwPZ5/SzOsDmMxOVrCyLblzpt+VmDDucYAOVjZLjZokk773jiYXW4gGqMjTla99zESxszEcXXgajxKixVEGGMEMZFv6nRcE7mIB/yI5q9I9nKVWNGhnnoL9VCQtbtGhdxdxs0AEjePz7LNp03TZjoNtDadClYcyAEoUxoEfV3fM+0pjTPhx/0pXEUJQihKEtmCEoRpkbAYShEkjYDCYhGkjZaBCUIkMJg0JoTpIBkyIhMgGSTpILSJOAkAiAQCAShOnQDBEAnASAQZAJwE4CJjZMfJ2CDPSbM8BHv+CUbWd420Jjrt6wlTpOkjwO+oOw6LqK3YgDZIvM2vmJ1J5AugfunIjLKRmdmYMuDiQTm2OpdJ1B1sCf+wmy6gU/0qAcQM7pgx9MvIny+/hH2dhQGNLiA4OY4kaHI1o8CZ9FDj6pqZRPeuSdmtLy6b2Jyxy46qpNM7ltHQLskNF3Gx3DSSYv0HkNVZdSJMNuASJ0BMkm5u6/35pqmKYwXF9I0AvoZtwsAeHSo/GvdqcrDYGTJ5D+Y84iNwjZaTOotFmhriNTHdBi5nQdbbBQYhzYAJuf7bkxwExv1Vd+Me8BrGgNG7haBq6AJPLS/BNRY6e/mJ6BgOh0g25yUK/0hLbkAAmNC0H2gqs/BVSJFM3/pzSd5gDlzWwMQf5Q0bQCB5Rqne8ES9xnafkjqp/4fM+ucfhTuyow8Cwx57eIVd7RtPit3EU2kSIHGCD4y6xWVVp5T3mH/ADa6R1IiD6JaVMv6pwlCn7pgA66SInp/tL9MHTX5aDolpUu1eEoUkJoQYITQjhKEACaEcJQjYRwkUZCaExoCUI0JQWgwkihOgIQE6ScIIkQCQCcBBkAiDfFEGcPLdE2meBQNABHA+f7ImNDjAIB3nboR9Xvy4RVeEgcTOyfAYfOTF8sdwESQZJLeJAGnAeCrGM88vka3ZVOH3ZM2cc02mbx0C7MdotaxxI4AgbCD6a/7XM4emWxlJPEkai1iBofuSr+HwbnnnpbnxVXhnJaLHYwvc5rNNQbHuxceMwmw2BeBmOp478PULewHYzGNOkn8EfdXX0WgaeXss7l/GuOH9cm7s2TneXG86gN9NotzUDqDA4uLZ2G8cAI0t7LexLRf/Xl83Wa+nB4cDPyPBHsr0Vshv3XGJJ0a1vHM491u2s81OxgmHPaDAJY15e4dXNOVvg48YhWKtNgaYcCGQQM2RpP8oc6J3nfe5JM50BwhhpzPeaGF8E7gvs5xN5I6cnOUXhK91I2aXF3Ahx9Ytve83uqWIZBh7HMnQ2ymOE3Pn4LQyVG2c7MAPpLA5s8oEs2sBtpwr1q+QFzGF/8AWwvIP/iRDtxEDSyei9qp5ngSx1joQdeQ/q8Dx8Kz8c3NFRvUhsOB46a9fNX6VCjWaX035HzBBGVzTGhM94cIHlCzcS2qyW1cr2gkQXC+3dnvNPLXiiQWhrZDYnfUNjUWM6XEWjgo3MBiHZtQHag8rE/bZQuYwgfXaG6CRewgT3bxqeFkdWnlIzbjXQHeZGhnX1jUlhzLRi0/ughJtQzB14x8+esrxb58hTZppjlKihKEUJJKBCZEQlCBoEJiEZCGEEGE0I4QkI2DJJ4STCEBEAkAnAQRAIgEgEbWoMgEJJNh+/h+ETx84KKpWDdz015WBsnInK8Kz3kkaQNdIg7Ec+JWp2TQvoW3kdTG8XFhzVSnh2vdmDwHHUR9z3Z5SZXT9mYJobG56RPGQtLdRzyXKtDA4UvMN5k7XBXQ0KIYIHmg7F7PyNO5O60TRCxytydWMmIGFRYp8BE8gef3VDGumAIvEXPj0skf1RrVJKhzo3Ya+3qfwpaeFOw8rKbF7ZeIpzNljYrDXmQLzB0P7wuqxGHLRosLtIOAmLdE8byjKbjNodovpmHPJbo0ZmgD+0SI30JhWK/aE99j4jVsaHdrm76GxvbUWWZVIdMtGl2w288C3KQfGLqhUsczTI+kg3tP0u3EW6WvYLojkvDdbUztc4OaHQDM6lpOW51aWl/dcRFiDFxE7FT3Ks6QHEZobFjYgO2g9IsZbhUK5Y6REjYklpE3aRrzkfutx7mVGh4B7sZ2mMzSRd0x3mkzfXiBEosKUNWmWAwC9kAyLkdOLNbTaJBF5ipvtFi096NiDv18JRYetkt9TDxsWnTXVtxqOFtEsQ1wbmbByugwB3munVo3B12OZuhlJcO6nItPK834Cb8OO10zH5TBgg2ngTsZ5oqVZvdMSNxqZ3B30+bKKrY6yHCeo4n1PJKxUuqlISLELGlsNcYn6J1I4nh46qUtPBZ2abY3cRQmhSwhISNFCRCMtQkJgBTIyEJQRkkkkBCAiATpwEwdoTp3JN+ckAhc8ZKoVwXG82J208dloOLQ24JJmA0hpi1yXA+yoVKtOZh8iQAXNcNNZi3kVeMY+S8GBM5WnLzNnX5mA0eIXcfwrQ7mZ7swa473LoEiZMjmDuFxWHrU7d10Dcvnw7rQYm8XXYDF5KLItLARcn6r6+KM+tF4u9u2odot0EcpFj0QVO0i52QQN3ERoPnuvNnYuoTOYD0QM7Ue10F4gxN4twhZ6be3LvK+JJIAtJ14AXURqy5pOl/wFg4DHOOZ7tCMjdzG59vJXhiGlhvrp5H8/NlIre43WNAMHS9/nyyN+MpsGy5LGdvOa4WuBFlk1+1nvvBja8jyRpPs7PE9sNOg8FhY55eCQI5fNFiU+0SDJPotOjjWvH1X4R90ep+zn+0GO1FiFRpuzAwLgyRMm+pE69NVs45ve0txWNXYWukQJ18eq1xvxhnPp6rGkSJEcvuD88FN2ZVh2sQIPn+YMH+lVS+L7fLRwQh2pFpF/C4Pp8lWy26Gm1rhOWDoY70G9i0niI1iAOShpOAJa4DK6LTYjx4GSDyM6KLCYkPaAbHR390ReOIhp8BwR1iS3M2A5t+Mxr7A34HqVpW0VakaboIsZvEAiAQ6NAdJA4o6xsCDdtrGJGoPr6KehUzDI7SS5lpymJc2DrFzxI5qm1jgcp2MSLiNug66JHKer3hJmbTfXgZVjD1M1t9+fRVnjhbXqIuZQtfDsw21HHiOqmzbTHLVaJCFGxwcJCYhZt+wEICFImITJGhIRkJkAEJkaSBpAEbAhARhMjxKRMApAJnj1Me6IVV6309PzI9SqJrFp7ruoIBB5FtwfHitDFWb5+QmfFZTxBN7z8K1x6YeTtawmHzZyDGVpsTHqdl02LADGtDXOgAACYAAiTG1lz/Y7Q55Y7+aBHIHvekld1haQiYtPIeajO8yL8c/G1W/hzsbOari0tbSpGo9+WXuIaXBrA4ECQDt5nTL7WP/ADuoseyu0Mz5gG5SMge5rXD6oFubgYuuvwPaTsM8uDc7HfWBct5QdRrbnrxwMS7Dl+ehhni899wYxkXBbNzxi8Qpl7XZ1pT7KwxLnUz/ACmLm+8jmtLHYMMEAkn5Cv4HClskxLjmEAyCYzFxNybARYDzUWPbLz5DwU28tNTXDkq+Ge+pkAubucdGt3JK0T2OW0y9lB72NDpfmf3sk53NAH0jc6CCiq4cOqOaXFrXWzCddg7Lfe3RdX2piG1cI2hQrNZkb+k4NeA2pSLbtdu0y0G44g6qt9I9eLfrhqVNlUHIx7ct3DMHwP6ri4/KgZhC11ngiJmCDHTxC6nsrEtw2HfTe9jhfKxsF0uu7vRuQBwEbysejWLw52k2Gg7o2vsgta77A8tLYi+82PqsjHUpB5LoMQJZ4wJsf3WbVpyI4onFK8ufY7Y8Z8wEnNyujj6I67A0kbz5a/keShqC3P3W8c1mj03FrrGCCtXCYkEjvZHDS1ieeuvDT3WVUuZ46+IlJzSIPEe23lCQ23KxDXghhYCQQJEEjSDsReNQZjTQcYyWgjUDLN5hsEHcgiY/8VBRr/UHyREkaiDBBjofkq3SqtdAJ1IAcCNpDSeIvlJN+OmUhxWoPc4AnXR1txp1kR1uoKgg2228bfOqeu0tda0G49wfY9FNVfIB0nxna/H9+aVVEmCqQY2OnI8PFXpWQyqARItvtF9o047rTw7y4SbEWI58RyWWU+t8Mvgi1MQiSIUNEZCBwUiYhUSNJPCSAhCIIQjagjlNU1HAT7IglUZ6fdEFUcc7ujmff4VmDWeHwLSxxsPmnwKlXYW2JF4dbnMek+a2x6cufa12K4frs6n1aQF6LgyMk2B6fcQQvK6Ty0hw1BBHUXXb0cZLWkGzhI6G6z8k5la+G8WLuMF5Y/ITuJM+qjwXZzs2d7y+CDpvx1KbAUv1H8hqtttEjugW3J+wUXKtpjKmwt7m0KhjiMxW03DBrZPVc/j35jZI1GtSzGRY/PVUqzXE96mH8wPGZ1BWgzMAC4SEg7UbFVKnKf1mNwxcRFPI3dx1JPr6LQdRYwQDw6dOaiDiHGRpvOvNQ1a25Pp7I2nUXK1DuiBrwgD0VDE04tyVtnaHdjUhUsXVzX4IpMHtNu6ptMi6udoglZ0rbHphn2NxEjhb2Ceq+QPE+JP4AQOPsPZDKpC+54Ia6JLmhh5FhAnrlyeZR4epMzrf8O8+74nqqlMzI2ufGD+/olnJJI1kk/lAbJAfZ31kQ102eIjKeBtY8oO0VaL47rri/UO+bfeFLRqtc2NzpaYtsN4uCBqD5QYgXk2JHGQR142N/NJewVIBgjThuOPzgrVCpF/+p/x5dFFXbmMRB1HiJyn2T0OHl1U1eNaodPPmElXwzzpsbjrw91aWVmnRjdwDghRwhKR0EJIoSTSrtCcBOE4QcEwpQnAROEj1/PoiCs3tFth5/PRZtUGBPDyubfOK18ey07/aReFlVak2McuIi0LbHpy+TtAt7saqXMLf6D6Okj1B81hStTsOp33N0zNt1bf2zIzm8S8V1lHS4Fz2U3vp/WBDRqZ5cVUw38RYsf8A2OBZMkuLQfA68bK/gXmWDgSfSB7raGCpudnyNz/1ZRPmsMbPrryxt6rBq/xG86mx2VKp26QJDCZW1232S14AjTQixHis538PAMgvdB4xw9E94psy+KTf4qquMGm0jSADK0G4prtoB9Dwnfj4FVGdkAHukjoYWh/8JrWFoNiDY+/Xn0T/AB+D8tflVfFv7n9wEjeyyXYybGVoU3EtyuF236g6+Gqo4rDBrwbQRIQmio1OaT3yo2MlSmyRxSxLLGeayHLWxWngVkuWuHTHyHcNOiFSVHT4W8FGCrZCYpyIuL5rg8NyPsoGnlPn9lO53dG2+nKPdvqgBo1MpkcQYVx47rXawTfi0nfiePKDuqFPX55q7hnScpAki1/TxEjx80cG15BBO3/ruPAoyb24qvOvKYHnYqdr2kwBlBuBOYAalpJ1SqpU4J26/Pm6vUnhwkeI4FZrH7GZHirNCqWmdjqPus8pttjlpbIQuRRN0zlDYCSSSZaQhE0IQpGhAFCdIIkgoY51rniPb/axDqtvtNtvET0Np9Viv1PVbYdOby9k1kg3Fttz0R0Kha4OGov+3khaRB42j7/byTnX08rKqznbscFiGhpcfpDcwjUg3+wTt/iSs8xRpEgf2z6myyuxKxy5TzjmOnIkLfdjns0aD6eyx1JeXXLuRVb2xiz9VGf+g18CChq9uVdKlJwH+J2tr1laI/iZgHfoEniCDtG91Xrdv0nfyOF5+kH7p8CWf1Vp9tUjq7LyIKndjWvbDXAxwPwqrWxWHfqwn/qPyqr8NS/la4HrA9EtQW/5XazYyuB0kHofnus/tCpLRy0Uj3FogmVXxDCW8UoV6FS0TveoGFSQiiK+JBIKyXC62nhZVcd5aYVl5J9QFJJJaMSU7Xd359JP2IHmVApKboPzexHigGPHz+cFJTqEEOG37/ZC9sXGh08Njz/PNPTIgjr/AKQF+o5pktH1QfGxPhb15KGiYMdY8PhTU3CSDpAE8O7lPzmlUbBM6iJHUXKSosOMHe2+6kpVDHMGxsoX6Bw+fumY6NOKmtMa0KL9p0v4KzKzp0I29v8ASu0XyOizyjbG/BpJSkkpAFIFGFKEAQCIIWowpUqdpt7h6fdc/lMxuukxw7sc/QBxWFhRNQdSfCCVth05vLN5RVBU1JpkTod1CrLB3RbifGRPhA9VdZTtYp5mODmjQ+Y/p6QulOJaWAjRwkfPmiw2YPOB6rSwlAtbli2o3hZZWV0YyxXrBxNpjioX0yOK0212gc1DXxQOynk+FJr+anZVUX6gJuEI5I0Sy4ZipXuAEWVVpy7oH1wgxvCZzrKMPJPAIHvlGhsTiFQxNO8q8xp3UWIpp48VGU2yUlYqUVAQtpdsbjYYJJJJpWKNSAQbjhzv+/ntqgLb20KAnb5KYFAXKQzQR48JHHkfujrE21y/TcacjwI0PRV8NUINiQdRuJ6c1Ze4OGa4JMOINrgEWOujvRIwUSQctr6Aoo3Hw8OUSo/0idO8d4uZ4xqN9VYY0wZBHGxsePr6pVUqWk+0b/PnipWPymdt1WYSDEaHnqCp9L8vf4VFa4/1oZgks+Y0McuCSn1a+yy1SBRtUgSMbUbUDUbVKlfHaHo7/wBT+Vj9mUC6oANYdbo0z7eq3KzCRH9rj7LI7CdFQHk70Y4rbD9a5vJ+0Zwbpz/MLoxhmiha2/mY9vZYlNv/ACMH+HrDvcrssRhgKJEfyx97eSeXwvHO1fsdgygfJgT7raOHEWGnJY3Z+DeGS0nVw8iR9lcZinCzlne286V8bgWOkkQeLSR7arHqdnNMw9wPOHAj0XQ4iuC1ZNU3EcEb0XrLeWFiKD2amRxCalXG5K26lMGQViYjDhpKcy32zyx10MVBtdTMZO6p04VxhSyESZUBspMyjISik1BNUZKbDFXHU06FGvh4AWbUZddHiWgt8PZYVdsEq5U2KbmoQEbik1Wysm0aSsNoo3Ybgl7QelVwYIIspw+ZA3gxEXGot1KidRcNkFweBCe9p1Z2mfaDrIuPDT1RUKhabEwjc3N3gOGYcCbZhyk+EgKEtItwuEG0Koae9oT9QGh/ubwUlJwNr6fPuqeGq8dvZSN7pt4KbF41aDPlkkOYcUlDXhaapAo2qQKWg2oghajClRqphj+ORwnxErncG/LJ4AkeLSPuFv436HEcD7t/PoucbaRxELbDpzeW/kmwkfrMnbIfJoP2XYVa8tI/tPsuNwn1tPL2Bb9lvvrQwnkUZ9wePqtrsqv/AMI5EnrLnfYqDFnNJGqp9nF2QSDED/1Cd9Uh0KLeWuM4Qtr6qHPLpUeIdBUmGpzdLQl5WCwkTxWfiacjotFj4sf9KniHD5ISh2bZRZBUjHpqrb2TNCpl1Uzn2SYVEApQEGmpNghXiqFF91eY6dEqYniyw8Ybrar1Q1p4rCqlVimqzkmBERKmpYc2Wm0eu6kpOsrDSjo4ZoF1N+g1ZXJrjihyBDUwgI0V5lFWKdEbpbV6z659tIscHAZgNRxB1B63vsndlc22o+k7Hi13A+ll0T8OCNFj4rBFsuZru2AQR0NvBXjn/WWXj1zGaLH3CtgZm7S3TmDeJ5G/ieSH9ZpAlo+3iDJ52OyYPGgseGxvt881oygs5GrSPApKPKdp8z+UktL3Ws1ShJJYukbU5SSUqQdsfSP8f/01YB08/ZJJb4dOXzfskoajofdyt1ahjU/Tx5FJJGScenX9iuJptkz3RrfZZWO1CSSzvbox/VQqq/gdAkkilCq/UVFi06SlVY9bVAEklUZ/U9NO5JJBibqrlDRJJAQY3VZWISSTxTUuFCuO2SSToiagrTdUklFaYpmqQpJKYu9CVR+/UJJJ0mHH/K7x+yqu180klvOo5L3U6SSSYf/Z" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <button onClick={increase}
          style={{
            background: "whitesmoke",
            padding: "5px",
            color: "black",
            fontSize: "25px",
            borderRadius: "10px",
            marginBottom: "20px",
            marginTop: "20px",
          }}
        >
          increment
        </button>
        <button onClick={decrease}
          style={{
            background: "whitesmoke",
            padding: "5px",
            color: "black",
            fontSize: "25px",
            borderRadius: "10px",
            marginBottom: "20px",
          }}
        >
          Decrement
        </button>
        <button onClick={obtainCount}
          style={{
            background: "whitesmoke",
            padding: "5px",
            color: "black",
            fontSize: "25px",
            borderRadius: "10px",
          }}
        >
          Get Count
        </button>{" "}
        <p
          style={{
            fontSize: "30px",
          }}
        >
          {" "}
          YOU HAVE ADDED {count} PERSON(s) TO THE DEATHNOTE
        </p>
      </main>

      <footer className={styles.footer}>
        <a href="https://www.rd.com/wp-content/uploads/2018/10/Creepy-clown.jpg?fit=700%2C467?fit=700,700" rel="noopener noreferrer" target="_blank">
          Ape_with_helmet greets thou
        </a>
      </footer>
    </div>
  );
};

export default Home;
